import TodoLayout from "./components/TodoLayout";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "TODO CHAKRA UI",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <TodoLayout/>
  );
}
